import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Cascadia_Code, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { DevelopmentNoticeModal } from "@/components/shared/DevelopmentNoticeModal";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-mono",
  display: "swap",
  fallback: ["ui-monospace", "monospace"],
});

const cascadiaCode = Cascadia_Code({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-serif",
  display: "swap",
  fallback: ["ui-monospace", "monospace"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "dark",
        "h-full",
        "antialiased",
        "font-mono",
        cascadiaCode.variable,
        jetbrainsMono.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <DevelopmentNoticeModal />
      </body>
    </html>
  );
}
